# Deep Learning with PyTorch


Author: [Anand Saha](http://teleported.in/)

### 1.7 Tensors on GPU

In [1]:
import torch

Check if your machine has GPU support

In [2]:
if torch.cuda.is_available():
    print("GPU Supported")
else:
    print("GPU Not Supported")

GPU Supported


Check the number of GPUs attached to this machine

In [3]:
torch.cuda.device_count()

1

Get device name

In [4]:
torch.cuda.get_device_name(0)

'Quadro T2000 with Max-Q Design'

Moving a Tensor to GPU

In [5]:
t = torch.FloatTensor([2, 3])

In [6]:
print(t)

tensor([2., 3.])


In [7]:
t = t.cuda(0)

Creating a Tensor on GPU, directly

In [8]:
t = torch.cuda.FloatTensor([2, 3])
print(t)

tensor([2., 3.], device='cuda:0')


Bring it back to CPU

In [10]:
t = t.cpu()
print(t)

tensor([2., 3.])


Use device context

In [11]:
with torch.cuda.device(0):
    t = torch.cuda.FloatTensor([2, 3])
    print(t)

tensor([2., 3.], device='cuda:0')


`Entire modules can be shifted to the GPU. We will see an example later when we create deep learning models.`